# pytorch_lightning==1.7.0
model:
  dims: 32
  lr: 0.003
  mn: 1
  ma: 15
  loss_type: logloss
data:
  batch_size: 128
  train_dataset_names:
    - Ihadoop
  test_dataset_names:
    - Ihadoop
  train_validation_proportions:
  - 0.8
  - 0.2
  noise_ratio: 0.0
  aot_ratio: 0.0
ckpt_path: null
